In [2]:
import numpy as np

In [4]:
# 1. np.array()
print("1. np.array()")
a = np.array([1, 2, 3, 4, 5])
print(a)

1. np.array()
[1 2 3 4 5]


In [8]:
# 2. np.zeros()
print("\n2. np.zeros()")
b = np.zeros((4, 3))
print(b)


2. np.zeros()
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# 3. np.ones()
print("\n3. np.ones()")
c = np.ones((3, 4))
print(c)


3. np.ones()
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
# 4. np.arange()
print("\n4. np.arange()")
d = np.arange(50, 100, 7 )
print(d)


4. np.arange()
[50 57 64 71 78 85 92 99]


In [22]:
# 5. np.linspace()
print("\n5. np.linspace()")
e = np.linspace(0, 10, 4)
print(e)


5. np.linspace()
[ 0.          3.33333333  6.66666667 10.        ]


In [28]:
# 6. np.random.rand()
print("\n6. np.random.rand()")
f = np.random.rand(2, 3)
print(f)


6. np.random.rand()
[[0.24967097 0.92391916 0.53694727]
 [0.53657064 0.30712382 0.96145359]]


In [19]:
# 7. reshape()
print("\n7. reshape()")
g = np.arange(6).reshape(2, 3)
print(g)


7. reshape()
[[0 1 2]
 [3 4 5]]


In [21]:
# 8. flatten()
print("\n8. flatten()")
h = np.array([[1, 2], [3, 4]])
print(h.flatten())


8. flatten()
[1 2 3 4]


In [23]:
# 9. transpose()
print("\n9. transpose()")
i = np.array([[1, 2], [3, 4]])
print(i.transpose())


9. transpose()
[[1 3]
 [2 4]]


In [32]:
# 10. concatenate()
print("\n10. concatenate()")
j1 = np.array([1, 2, 3])
j2 = np.array([4, 5, 6])
print(np.concatenate((j1, j2)))
print(np.concatenate((j2, j1)))


10. concatenate()
[1 2 3 4 5 6]
[4 5 6 1 2 3]


In [36]:
# 11. split()
print("\n11. split()")
k = np.array([1, 2, 3, 4, 5, 6])
print(np.split(k, 2))


11. split()
[array([1, 2, 3]), array([4, 5, 6])]
