In [1]:
import numpy as np

In [ ]:
pip install numpy

In [3]:
a = np.array([1,2,3,4,5])

In [5]:
a

array([1, 2, 3, 4, 5])

In [7]:
# Creating arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
a.shape

(5,)

In [11]:
b.shape

(2, 3)

In [13]:
a.ndim

1

In [15]:
b.ndim

2

In [17]:
a.dtype

dtype('int32')

In [19]:
z= np.array([1, 2, 3, 4, 5],dtype= float)
z

array([1., 2., 3., 4., 5.])

In [21]:
z.dtype

dtype('float64')

In [23]:
print("1D array:", a)
print("2D array:\n", b)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]


In [25]:
# Array operations
print("\nArray addition:", a + 2)
print("Array multiplication:", a * 2)


Array addition: [3 4 5 6 7]
Array multiplication: [ 2  4  6  8 10]


In [27]:
# Mathematical functions
print("\nSine of array:", np.sin(a))


Sine of array: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [29]:
# Statistical operations
print("\nMean of array:", np.mean(a))
print("Standard deviation of array:", np.std(a))


Mean of array: 3.0
Standard deviation of array: 1.4142135623730951


In [31]:
# Statistical operations
print("\nMean of array:", np.mean(b))
print("Standard deviation of array:", np.std(b))


Mean of array: 3.5
Standard deviation of array: 1.707825127659933


In [33]:
# Reshaping arrays
a.shape
c = a.reshape(5, 1)
print("\nReshaped array:\n", c)



Reshaped array:
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [35]:
# Matrix operations
d = np.array([[1, 2], [3, 4]])
e = np.array([[5, 6], [7, 8]])
print("\nMatrix multiplication:\n", np.dot(d, e))


Matrix multiplication:
 [[19 22]
 [43 50]]


In [39]:
print("\nMatrix multiplication:\n", np.dot(e,d))


Matrix multiplication:
 [[23 34]
 [31 46]]
